### ISSUE TITLE
refresh_token used in config_flow.py

### ISSUE THREAD

**Issue by robertteir** [selleronom/mittfortum#1]
Hi,

First off awesome work and thank you!

I think the refresh_token is used in the test in config_flow.py, so it is already used and then the integration fails.

I was able to make it work by manually setting a new refresh_token in core.config_entries and then reloading HA.

**Comment by selleronom** [comment]
Thank you!

I am testing the approach of using refresh_tokens instead of the previous username / password login flow after MittFortum changed their login method. I will work on cleaning up the code for using refresh_token after a week of testing ;)

**Comment by Jerra94** [comment]
Hi,
I'm trying to add this integration but I having issues configuring it.
How do I obtain the refresh token?
How do I configure this integration, is the only way via the file /config/custom_components/mittfortum/strings.json?

**Comment by selleronom** [comment]
@Jerra94 You can find your refresh_token by using a browser:

1. Open 'Networks' tab in 'Web developer tools'
2. Login to MittFortum
3. Search for 'access_token'
4. Check the 'Response'
5. Copy 'refresh_token'
6. Use 'refresh_token' as the 'username' for the integration

![image](https://github.com/selleronom/mittfortum/assets/3093210/58e987c2-f730-4220-a85b-40f19c719405)
